### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by qeeji** [theodox/standaloneRPC#1]
Hi , 

I'm totally newbee for this kind of remote procedure , I headed an issue which I can't fix .

Here are the things I did : (under windows 8.1) 
1 ,open command line and type command : mayapy.exe C:/Python27/Lib/site-packages/standaloneRPC.py
  works fine and showed me the service in task Manager 
2 , run command in maya2017
import sys
sys.path.append('C:\Python27\Lib\site-packages')
import standaloneRPC as srpc
cmd = srpc.CMD('cmds.ls', type='transform')
srpc.send_command(cmd)

Then I got an error : # Error: HTTPError: file C:\Program Files\Autodesk\Maya2017\bin\python27.zip\urllib2.py line 558: HTTP Error 503: Service Unavailable # 

I'm appreciate if you can take a look and figure me out .

Thanks a lot !

**Comment by theodox** [comment]
That sounds like the port is not properly getting set -- maybe something else on your machine is using TCP port 8000

When you run step one, do you get the ouput `starting server on 8000` or something similar?  

Before trying the command, see if you can ping 127.0.0.1:8000 -- if you get a response, it means port 8000 is already in use.

**Comment by qeeji** [comment]
Yes I got 'starting server on 8000' , just got error when I run script in maya , will try another port number , thanks!

**Comment by qeeji** [comment]
My host IP is 192.168.2.110 which is not 127.0.0.1 , dose this matter?

**Comment by qeeji** [comment]
Yeah , I made it work 
import socket
import standaloneRPC as srpc
cmd = srpc.CMD('cmds.ls', type='transform')
srpc.send_command(cmd , socket.gethostbyname( socket.gethostname() ) )


Cheers,
